### ISSUE TITLE
sqlite3 module not being detected

### ISSUE THREAD

**Issue by Sledmine** [nodemcu/nodemcu-firmware#2913] opened 2019-09-13 03:22 UTC
Hi, i'm using the latest NodeMCU firmware build from the Cloud build service:
```
branch: master
        commit: 310faf7fcc9130a296f7f17021d48c6d717f5fb6
        release: 3.0-master_20190907
        release DTS: 201909070945
        SSL: false
        build type: float
        LFS: 0x0
        modules: color_utils,cron,file,gpio,http,net,node,pwm,sjson,sqlite3,tmr,                                                                                                                                                             uart,websocket,wifi,wifi_monitor
```

For some reason sqlite3 is not being detected as a module at all, running the example from the readthedocs.io just says "sqlite3" is nil.

```
dbtest.lua:1: attempt to index global 'sqlite3' (a nil value)
stack traceback:
        dbtest.lua:1: in main chunk
        [C]: in function 'dofile'
        stdin:1: in main chunk
```
Code used to test sqlite3:
```lua
db = sqlite3.open_memory()

db:exec[[
  CREATE TABLE test (id INTEGER PRIMARY KEY, content);

  INSERT INTO test VALUES (NULL, 'Hello, World');
  INSERT INTO test VALUES (NULL, 'Hello, Lua');
  INSERT INTO test VALUES (NULL, 'Hello, Sqlite3')
]]

for row in db:nrows("SELECT * FROM test") do
  print(row.id, row.content)
end
```

Is there something changed in this build that is messing with the module?

**Comment by galjonsfigur** [comment] 2019-09-13 07:29
`sqlite3` module was disabled due to large changes in NodeMCU Lua VM recently (see on [git blame](https://github.com/nodemcu/nodemcu-firmware/blame/310faf7fcc9130a296f7f17021d48c6d717f5fb6/app/modules/sqlite3.c#L28)) so it's impossible to build firmware with it without removing `#if 0` and corresponding `#endif` in `sqlite3.c` file. You could try using any version before commit https://github.com/nodemcu/nodemcu-firmware/commit/1990f95740e9f7d375b1157a25d0b6b508586c27 - it should at least be able to compile.

**Comment by marcelstoer** [comment] 2019-09-13 12:00
To my knowledge there has never been any consensus that want to really disable it. This `#if 0` comes as a complete surprise (at least to), I wasn't aware of it.

**Comment by Sledmine** [comment] 2019-09-13 15:34
Oh i see now, so there are not any chances to get it back in future releases?, i always recommend people to use the cloud build service to avoid large setup and start developing with NodeMCU fast as possible, as far as i know in this service is not possible to choose which commit you are going to use from the branch, so this basically means, "compile it by yourself" and is not a problem for me, but i try to bring it to less experienced people as a way to "go fast".

**Comment by TerryE** [comment] 2019-09-13 18:05
Marcel, I `#if 0` the body of sqlite3 because doing the work to get it to run with all of my API updates was going to be a total PITA.   As I have said in previous discussions, I have always challenged why on earth we added some untested university project to our base libraries.  

I don't have an issue with sqlite3 per se.  The issue is that our 45Kb RAM is already well under the recommended minimum buffer allocation for sqlite3.  It might be a viable module for the ESP32, but IMO no one will be able to get a usable real-world application using this library running on the ESP8266.

No one has demonstrate such an application.  If @Sledmine can produce such a demonstrator then perhaps I might be inclined to do this work.

**Comment by marcelstoer** [comment] 2019-09-13 20:11
We have gone over the arguments for/against this module a number of times. Maybe we should just agree to disagree 😉.

However, since #2300 is still open nobody would expect that the module isn't built into the firmware even if you enable it. This is a breaking change without PR (just buried in a much larger PR) and, therefore, there's no mention in the release notes. Worse, it's now on master like that and that will affect our largest user base - those building with cloud builder.

I don't know what the best way out of this is at the moment.

**Comment by TerryE** [comment] 2019-09-13 21:00
> Maybe we should just agree to disagree

Marcel, I've given you my reasons why I think that this module is unworkable in the real world. See the configuration guidelines and the code for yourself.  The simplest way to convince me is by evidence: why not build a small but realistic application say a logging application that is collecting data from some DS18B20s and logging it into a SQLite3 D/B which can be queried using a simple HTTP request protocol?  

The effort to do this is tiny compared to my Lua 5.3 program and also smaller than the effort needed to update the module itself.  If someone, _anyone_ can show me a real working application using this module then I will offer my support.

As far as I am concerned we've added it because it compiles clean and works with a noddy test which adds a row to a table.

**Comment by Sledmine** [comment] 2019-09-16 16:42
Sure, i was looking for a fix for the module to implement it in a little project, it was not a project that serious but if you want to have a full working example, of course, i'm going to be working on it this week

**Comment by TerryE** [comment] 2019-09-16 22:34
@Sledmine, if you need sqlite3 then use the last 2.2.1 release. Note that `node.heap()` gives about 43Kb free, but the recommended default minimum workspace for sqlite3 alone is 64K.

I will be interested what
```Lua
db = sqlite3.open_memory()
db:exec('CREATE TABLE test (id INTEGER PRIMARY KEY, content);')
print(node.heap())
```
gives you as the free RAM.

**Comment by HHHartmann** [comment] 2019-09-29 19:39
> However, since #2300 is still open nobody would expect that the module isn't built into the firmware even if you enable it. This is a breaking change without PR (just buried in a much larger PR) and, therefore, there's no mention in the release notes. Worse, it's now on master like that and that will affect our largest user base - those building with cloud builder.
> 
> I don't know what the best way out of this is at the moment.

Currently this is a bug on master, so we should get a consistent solution here.
Do we have a "Known Bugs" section somewhere?
We also have changed master before, so we should either fix the documentation or remove the `#if 0` on master. If I read you correctly @TerryE it is still buildable on master.

Do we move the release tag then also or have an in between release. There are maybe also some other regression bugs that might go on master before the next release.

**Comment by TerryE** [comment] 2019-09-29 21:18
> If I read you correctly @TerryE it is still buildable on master.

No, it is commented out on master.   

>  **If someone, _anyone_ can show me a real working application using this module then I will offer my support.**

I am still deafened by the silence here,  I have yet hear from _anyone_ that this is any more than an academic exercise, and provide an argument that we have enough RAM on the ESP8266 to be able to build a meaningful application.  So I hardly think this is a priority.  It works in as much as is ever going to on the 2.2.1, and this has slightly more heap available than the SDK 3.0 releases, so this is a perfectly practical workaround.  We have a lot more importing issues to close.  At a minimum we should get the Lua 53 release into `dev`.

**Comment by luizfeliperj** [comment] 2019-10-28 15:37
Wow! I was unaware those API changes already took place, I will take a look. Is there a guide to help developers to move from the previous API to the current?

**Comment by HHHartmann** [comment] 2019-12-27 14:02
So how to preceed here? At least the documentation should reflect the code, so I would like to link this issue in the documentation and make it clear that sqlite3 is not available atm.

**Comment by Shubham9918** [comment] 2020-01-08 19:32
Is any alternate way to store data locally in ESP8266, because I need an application with store data locally for node management.

**Comment by Shubham9918** [comment] 2020-01-08 19:32
Is any alternate way to store data locally in ESP8266, because I need an application with store data locally for node management.

**Comment by TerryE** [comment] 2020-01-08 21:50
A JSON serialised array?

**Closed** 2020-06-10 06:23 UTC
Labels: bug
