### ISSUE TITLE
srv:close() want free memory...

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#2043] opened 2017-07-14 07:32 UTC
The srv:close() function works it shut down the server but it does not free the memory.
Is it a bug?

**Comment by Aterocana** [comment] 2017-07-14 07:41
Are you talking of a regular TCP server? I noticed that too.

**Comment by chathurangawijetunge** [comment] 2017-07-14 10:34
Yes regular TCP server...

**Comment by marcelstoer** [comment] 2017-07-14 19:45
@chathurangawijetunge / @Aterocana What branch or firmware version? Do you have a reproducible test case?

**Comment by chathurangawijetunge** [comment] 2017-07-15 01:13
Firmware- custom build (cloud)
Branch- dev

I'm trying to set up a TCP server on port 80 and get some user data.
After getting the data I want to close the server on port 80 and open a nother server on a different port.
Srv: close() does the job...
But it want free the memory acquired by the previous server
Is it a bug?

**Comment by Aterocana** [comment] 2017-07-15 07:20
Monday I'll prepare a reproducible test on branch master. Thanks.

**Comment by TerryE** [comment] 2017-07-16 10:43
The usual issue here is programmer error, and not a bug; e.g. you are closing the upvalue rather than the local copy.  This leaves a dangling reference in the registry so the `__gc` method isn't fired.

**Comment by chathurangawijetunge** [comment] 2017-07-16 11:11
So then how to close a TCP server property....

**Comment by chathurangawijetunge** [comment] 2017-07-16 11:15
So then how to close a TCP server property....
Clearing all local copies....

**Comment by TerryE** [comment] 2017-07-16 11:43
Sorry but this is standard Lua, so please read the FAQ and see the documentation [example 3](https://nodemcu.readthedocs.io/en/master/en/modules/net/#example_3).  Note that the `net.socket` close uses `sck` not `conn`or  `sv` and thememory won't be fully released until you stop the server as well.

**Closed by TerryE** 2017-07-16 11:43 UTC

**Comment by chathurangawijetunge** [comment] 2017-07-17 04:48
Still same issue...

**Comment by marcelstoer** [comment] 2017-07-17 07:49
> The usual issue here is programmer error

That was my initial reaction as well. @chathurangawijetunge that's why we're insisting on self-contained test cases (i.e. Lua code) in our issue template.

**Comment by chathurangawijetunge** [comment] 2017-07-17 15:23
Found a way.... by calling

Conn:on("recive",nill)
Conn:on("sent",nill)
Before
Conn:close()
