### ISSUE TITLE
MQTT BUG??

### ISSUE THREAD

**Issue by chathurangawijetunge** [nodemcu/nodemcu-firmware#2245] opened 2018-02-02 00:43 UTC
hi i am using the code

m = mqtt.Client(node.chipid(), 5, "", "")
m:lwt("/lwt", "offline", 0, 0)
m:on("connect", function(client) print ("connected") end)
m:on("offline", function(client) print ("offline") end)

-- on publish message receive event
m:on("message", function(client, topic, data) 
  print("incomming...",topic .. ":" ) 
  if data ~= nil then
    print(data)
  end
end)

function connect()
  print("connecting.....")
  m:connect("broker.hivemq.com", 1883, 0, function(client)
    print("connected")

    client:subscribe("/sw1", 0, function(client) print("subscribe success") end)
    client:publish("/sw1", "hello", 0, 0, function(client) print("sent") end)
  end,
  function(client, reason)
    print("failed reason: " .. reason)
    tmr.alarm(6,2000, 0, function() connect() end)
  end)
end

connect()
-----------------------------------------------------

this works fine... 
until i remove the phone line from my rougher and re connects after some time this code re connects to the MQTT broker.
but after 5 seconds it fires the offline function and reconnects, this happens every 5 seconds there after...
is it a bug????

**Comment by FrankX0** [comment] 2018-02-02 08:07
Sounds like a duplicate of #2197.

**Comment by chathurangawijetunge** [comment] 2018-02-02 10:41
So is it a bug ?

**Comment by FrankX0** [comment] 2018-02-02 11:55
In my opinion: yes.

**Comment by chathurangawijetunge** [comment] 2018-02-04 01:31
So how can we sort out this issue (bug)

**Closed** 2018-02-04 07:27 UTC
Labels: duplicate

**Comment by chathurangawijetunge** [comment] 2018-02-04 12:40
Will this be fix any time sooner
