### ISSUE TITLE
FR: add  ability to store custom configs  to enduser setup

### ISSUE THREAD

**Issue by pastukhov** [nodemcu/nodemcu-firmware#1650] opened 2016-12-06 08:35 UTC
### Missing feature
Neduser setup is able to use custom html page, but not able to store anything, except SSID and password.
### Justification
The idea is: to be able to store additional fields of eunduser setup form. For example with wifi_ssid=blablabla&wifi_password=123&custom_config={option1:1,option2:2}, urlencoded and stringifyed. Then the module should save it to custom_config.json or similar.

**Comment by marcelstoer** [comment] 2016-12-07 11:29
To me this looks a close duplicate of #1302.

**Closed** 2016-12-11 20:04 UTC
Labels: duplicate
