### ISSUE TITLE
Sample code for MQTT causes esp8266 restarting like crazy(using new firmware)

### ISSUE THREAD

**Issue by ErfanThinker** [nodemcu/nodemcu-firmware#1456] opened 2016-08-14 14:21 UTC
Hi, I used the firmware generated in cloud service and flashed my esp8266 with it. then tried to save this code to it:
```
function onSuccess(client)
    m:subscribe("/topic",0, function(client) print("subscribe success") end)
    m:publish("/topic","hello",0,0, function(client) print("sent") end)
end

-- init mqtt client with keepalive timer 120sec
m = mqtt.Client("clientid", 120, "user", "password")

-- setup Last Will and Testament (optional)
-- Broker will publish a message with qos = 0, retain = 0, data = "offline" 
-- to topic "/lwt" if client don't send keepalive packet
m:lwt("/lwt", "offline", 0, 0)

m:on("connect", function(client) print ("connected") end)
m:on("offline", function(client) print ("offline") end)

-- on publish message receive event
m:on("message", function(client, topic, data) 
  print(topic .. ":" ) 
  if data ~= nil then
    print(data)
  end
end)

-- for TLS: m:connect("192.168.11.118", secure-port, 1)
m:connect("192.168.11.118", 1883, 0, function(client) print("connected")
                                        onSuccess(client)
                                        end, 
                                     function(client, reason) print("failed reason: "..reason) end)

-- Calling subscribe/publish only makes sense once the connection
-- was successfully established. In a real-world application you want
-- move those into the 'connect' callback or make otherwise sure the 
-- connection was established.

-- subscribe topic with qos = 0
--m:subscribe("/topic",0, function(client) print("subscribe success") end)
-- publish a message with data = hello, QoS = 0, retain = 0


m:close();
-- you can call m:connect again
```
and my nodemcu started to restart at rate of 2-3  per sec. 
I managed to flash it by chance(barely) and tried to send this code again to my esp again and it didn't happen again, but then again I gave code to my pal @jimeni72 and he tried to do the same with his nodemcu and phenomena happened to his device too.
Please help.

**Comment by NicolSpies** [comment] 2016-08-14 16:46
I have tested on my code and not experiencing the same. I think the problem is in your onSucess(client) function where publish is called before subscribed has completed.

**Comment by djphoenix** [comment] 2016-08-14 16:50
@NicolSpies nope. Publish message is *queued* to send after subscribe...
Tested this sample code, no issues found (latest dev with my patch merged). Try to rebuild firmware in cloud, it should just work.

**Comment by ErfanThinker** [comment] 2016-08-14 17:12
@NicolSpies  @djphoenix  I just built the firmware like 16 hours ago from [here](http://nodemcu-build.com/) and twice, as I said for the first time it caused the phenomena and after a second flash it went okay, but for my pal it caused the problem again. so it is causing the problem by chance or something I guess?

**Comment by djphoenix** [comment] 2016-08-14 17:46
> like 16 hours ago

So #1445 was merged 9 hours ago. Please try with latest build, it should be more stable for MQTT.

**Comment by ErfanThinker** [comment] 2016-08-14 17:53
@djphoenix I'll try to see if it'll do any good, thanks for help :)

**Comment by hwmland** [comment] 2016-08-14 17:54
Did you flash new esp_init_data_default.bin as well?

**Comment by ErfanThinker** [comment] 2016-08-14 17:55
@hwmland no, what is it for and where can I get it?

**Comment by hwmland** [comment] 2016-08-14 17:59
@ErfanThinker Try to read instructions [here](http://nodemcu.readthedocs.io/en/master/en/flash/)

**Comment by marcelstoer** [comment] 2016-08-14 20:13
See http://nodemcu.readthedocs.io/en/latest/en/support/ and #1010.

**Closed by marcelstoer** 2016-08-14 20:13 UTC

**Comment by ErfanThinker** [comment] 2016-08-14 20:16
@djphoenix tried latest build, the same happend again. don't know whats wrong.
