### ISSUE TITLE
node.bootreason() after rtctime.dsleep () gives wrong boot reason

### ISSUE THREAD

**Issue by eyaleb** [nodemcu/nodemcu-firmware#1606] opened 2016-11-21 08:34 UTC
The reason returned by `node.bootreason()` on wakeup from `rtctime.dsleep ()` is not as expected.
The reason returned after `node.dsleep()` is correct.
### Expected behavior
```
2       5
```
### Actual behavior
```
2       6
```
### Test code
Running this command:
```Lua
= node.bootreason()
```
after the different restart modes listed gives the following output
```
power-up                2 6
reset                   2 6
WDT timeout             2 3
node.restart()          2 4
node.dsleep() wakeup    2 5
rtctime.dsleep() wakeup 2 6
```

The last is the inconsistent one.

You may ask why I use this dsleep? Because it is faster and on battery every ms counts.

### NodeMCU version
Latest dev. Latest commit c54bc05 .

### Hardware
I see it on multiple devices, now on esp-12e.

**Comment by jmattsson** [comment] 2016-11-21 23:31
Duplicate of #1039. Ifaik nobody has reverse-engineered stuff enough to work out where the SDK sets the flag/value to use for bootreason after deep-wakeup.

**Closed by jmattsson** 2016-11-21 23:31 UTC
