### ISSUE TITLE
ws2812-module drives 1st pixel incorrectly

### ISSUE THREAD

**Issue by milkpirate** [nodemcu/nodemcu-firmware#621] opened 2015-08-29 15:47 UTC
Hey,

I'm having issues with the ws2812-module. All pixels > 1 are fine but pixel = 1 makes problems. It seems to have the green channel always at 255, doesnt matter what "color" is written to it. All the other pixels work like a charm. I already tried to rearange them (exchange the first pixel) but the problem persits. So I guess its related to the software side.

```
NodeMCU custom build by frightanic.com
	branch: master
	commit: 474ae33288f82f79d1e6cec907a6c842e188487b
	SSL: false
	modules: node,file,gpio,wifi,net,i2c,tmr,uart,bit,ws2812
 	built on: 2015-08-24 16:25
  powered by Lua 5.1.4
set 	(mode=1)
MAC: 	18:fe:34:xx:xx:xx
chip: 	10032807
heap: 	30000
> IP: 	192.168.177.45
nodemcu-httpserver running at http://192.168.177.45:80
> ws2812.writergb(4, string.char(100):rep(3*10))
> ws2812.writergb(4, string.char(10):rep(3*10))
> ws2812.writergb(4, string.char(255):rep(3*10))
> ws2812.writergb(4, string.char(5):rep(3*10))
> ws2812.writergb(4, string.char(10):rep(3*10))
```

The last write is visible on that picture (the whites are really dimm but the 1st one is fully green)

![img_20150827_185120](https://cloud.githubusercontent.com/assets/9251021/9562748/c5bf95ee-4e75-11e5-8fcb-6a14fd441016.jpg)

As usual I really appreciate any help.

**Comment by Aeprox** [comment] 2015-08-29 16:30
Duplicate of #487? Supposedly fixed in PR #548. It's not merged into master yet so you'll need to build it yourself from dev branch.

**Closed** 2015-08-29 16:36 UTC
