### ISSUE TITLE
wifi.c file have a bug

### ISSUE THREAD

**Issue by yangyongda** [nodemcu/nodemcu-firmware#2952] opened 2019-11-01 14:13 UTC
when WIFI_SMART_ENABLE is uncomment,  #include "smart/smartconfig.h" will build error,  because smart directory found not smartconfig.h file.  
 you can try

**Comment by yangyongda** [comment] 2019-11-01 14:20
#ifdef WIFI_SMART_ENABLE
#include "smart/smart.h"
#include "smart/smartconfig.h" 

static int wifi_smart_succeed = LUA_NOREF;
#endif

please check  #include "smart/smartconfig.h"

**Comment by TerryE** [comment] 2019-11-02 07:31
Duplicate of #2928

**Closed by TerryE** 2019-11-02 07:31 UTC
