### ISSUE TITLE
Timer tmr.time() does not work properly

### ISSUE THREAD

**Issue by milikiller** [nodemcu/nodemcu-firmware#132] opened 2015-01-25 22:29 UTC
Hi. I have problem with tmr.time()  I write simple script, for periodicaly write actual time, and time is not correct printed.

code:

    tmr.alarm(0, 500, 1, function()
      print(tmr.time())
    end)

output:

    2105
    2104
    2105
    2104
    2105
    2105
    2106
    2107
    2108
    2110
    2108
    2108
    2109
    2109
    2110
    2111
    2112
    2113
    2112
    2112
    2112
    2113
    2113
    2114
    2114
    2115

**Comment by nodemcu** [comment] 2015-01-25 22:42
confirmed, this is because apply vary cal value to a big count number. can be fixed in next build

**Closed** 2015-01-27 12:48 UTC
