### ISSUE TITLE
Code not returning correct temperature value.

### ISSUE THREAD

**Issue by aditgupta100** [nodemcu/nodemcu-firmware#1959] opened 2017-05-06 13:57 UTC
Make sure you read and understand http://nodemcu.readthedocs.io/en/dev/en/support/.
Use one of the two templates below and delete the rest.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
Temperature data should be correct.

### Actual behavior
ds18b20 is giving temperature 34 while the expected temperature of the room is 25.

### Test code
```
    require('ds18b20') 
    ds18b20.setup(1) 
    temp_data=ds18b20.read()
    temp_data=ds18b20.read()
    print("Temp:"..temp_data.." C\n")
```

### NodeMCU version
```
NodeMCU custom build by frightanic.com
	branch: master
	commit: 22e1adc4b06c931797539b986c85e229e5942a5f

```

### Hardware
ESP8266 Nodemcu dev-board

8<------------------------ END BUG REPORT -------------------------------------

**Comment by FrankX0** [comment] 2017-05-07 11:48
Sorry, cannot reproduce your findings.
Because the FW only handles the OW protocol, your results mainly depend on the ds18b20.lua module.
Please check whether the issue is generated from this module.

**Comment by FrankX0** [comment] 2017-05-12 10:45
@aditgupta100: any progress on this issue?

**Comment by marcelstoer** [comment] 2017-05-16 15:02
No feedback from author in ten days -> closing

**Closed by marcelstoer** 2017-05-16 15:02 UTC
