### ISSUE TITLE
dht module returns checksum errors/weird values

### ISSUE THREAD

**Issue by wilhelmy** [nodemcu/nodemcu-firmware#3328] opened 2020-11-12 17:44 UTC
I recently updated, now I'm getting checksum errors with the dht module.

On the old firmware, I suspect the readings are way off, more than the ±2°C tolerance which are specified for the sensor iirc. Is this normal?

In case it matters, this is a WeMos D1 mini and 3 DHT11 sensors.

### Expected behavior

NodeMCU 3.0.0.0 
	branch: master
	commit: 3d917850180f67adc7f2c6b5d00f27c152e7194c
	release: 3.0-master_20190907 +2
	release DTS: 202002231746
	SSL: false
	build type: float
	LFS: 0x0
	modules: adc,bit,dht,file,gpio,i2c,mqtt,net,node,ow,spi,tmr,uart,wifi
 build 2020-03-17 02:44 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
lua: cannot open init.lua
   
> 
> for i=5,7 do print(dht.read11(i)) end
0	24	34	0	0
0	25	33	0	0
0	23	38	0	0

### Actual behavior
NodeMCU 3.0.0.0 
	branch: master
	commit: 4f6792773f93f36a7255cfd28dca7aa6c4aa9552
	release: 3.0-release_20201107
	release DTS: 202011071523
	SSL: false
	build type: float
	LFS: 0x0 bytes total capacity
	modules: adc,bit,dht,file,gpio,i2c,mqtt,net,node,ow,spi,tmr,uart,wifi
 build 2020-11-12 01:20 powered by Lua 5.1.4 on SDK 3.0.1-dev(fce080e)
cannot open init.lua: 
> for i=5,7 do print(dht.read11(i)) end
0	614.4	870.4	400	400
-1	614.4	896	400	0
-1	742.4	1203.2	400	200
> for i=5,7 do print(dht.read11(i)) end
-1	793.6	1203.2	600	200
-1	793.6	1203.2	600	200
-1	793.6	1203.2	600	200
> for i=5,7 do print(dht.read11(i)) end
-2	-999	-999	0	0
-2	-999	-999	0	0
-2	-999	-999	0	0
> for i=5,7 do print(dht.read11(i)) end
-1	793.6	1203.2	600	200
-1	793.6	1203.2	600	200
-1	793.6	1203.2	600	200
> for i=5,7 do print(dht.read11(i)) end
-2	-999	-999	0	0
-2	-999	-999	0	0
-2	-999	-999	0	0
> for i=5,7 do print(dht.read11(i)) end
-1	793.6	1203.2	600	200
-1	793.6	1203.2	600	200
-1	793.6	1203.2	600	200

**Comment by marcelstoer** [comment] 2020-11-14 21:00
Related to @emdioh's #3210?

**Comment by ezbella** [comment] 2020-11-16 20:35
I'm facing the same issue with the latest version of dht module. More details here: [https://github.com/nodemcu/nodemcu-firmware/pull/3210#issuecomment-727264396](url)
Which is the recommended way of building the firmware but using the previous working version of dht module?
Thanks in advance for your wisdom! =)

**Comment by vsky279** [comment] 2020-11-21 20:27
I confirm the issue is due to #3210. I'll try to fix it in coming days.

**Comment by wilhelmy** [comment] 2020-12-14 21:10
Would it be possible to merge this into master?

**Comment by marcelstoer** [comment] 2020-12-14 21:14
#3334 will soon be merged - to `dev`. Once we release it, planned at the end of this month, it'll be available on `release` and `master`. See https://github.com/nodemcu/nodemcu-firmware/tree/dev#releases for details.

**Comment by jmiskovic** [comment] 2020-12-16 18:23
I also ran against this issue with DHT22 and #3334 solved it! Thanks for the fix.

**Closed** 2020-12-16 22:07 UTC
