### ISSUE TITLE
Issue with integer management in runtime

### ISSUE THREAD

**Issue by landswipe** [nodemcu/nodemcu-firmware#1957] opened 2017-05-06 08:18 UTC
### Expected behavior
If the 31st bit is set, it shouldn't cause the variable to become 0XFFFFFFFFF

### Actual behavior
See test code, just comment out either first or second line to feed value v differently. First line works fine without the 31st bit set, second line results in the value being 0xFFFFFFFF (incorrectly).

Interestingly the second invocation to bit.set(v,31) works fine indicating the problem is with the initial parsing of the value (still into the function) and not the internal checkInteger function itself (although I might be wrong). I have tested this with both bit and rfswitch (where I found it) modules, so it's not the module.

### Test code
```Lua
--v=0x7555AAAA  -- WORKS
v=0xF555AAAA  -- FAILS and trashes value with 0xFFFFFFFF

print(string.format("%X\n", v)) -- Works in both cases
v=bit.set(v,31)
print(string.format("%X\n", v)) -- Fails in v=F555AAAA case, ok in v=7555AAAA
v=bit.set(v,31) 
print(string.format("%X\n", v))  -- Second invocation in v=7555AAAA case is fine (it was set F555AAAA in prior bit.set() call)
```
### NodeMCU version
master, 22e1adc4b06c931797539b986c85e229e5942a5f

### Hardware
NodeMCU, ESP8266, 4MB flash

**Comment by FrankX0** [comment] 2017-05-07 12:28
I can confirm this result, but only with a float build: with an integer build it works correctly.
In addition, it only fails when initially bit 31 is already set.
My guess is that this is caused by internal float representation and that your example can only work with an integer build.

**Comment by landswipe** [comment] 2017-05-07 13:03
Thanks for checking, I'm fairly new to the codebase and couldn't work out how to generate float vs integer images, can you let me know where it is configured?

**Comment by FrankX0** [comment] 2017-05-07 14:20
You can uncomment the following [line](https://github.com/nodemcu/nodemcu-firmware/blob/master/app/include/user_config.h#L93) in `app/include/user_config.h`:
`#define LUA_NUMBER_INTEGRAL`

**Comment by landswipe** [comment] 2017-05-07 14:44
Thanks :)

**Comment by FrankX0** [comment] 2017-05-08 20:34
Creating an integer build is now documented.
Please close this issue.

**Closed** 2017-05-09 06:26 UTC

**Comment by landswipe** [comment] 2017-05-10 11:55
Thanks Frank, so this behaviour is expected on float builds?

**Comment by FrankX0** [comment] 2017-05-12 10:52
Sorry, don't know.
I do not know how Lua is handling floats and integers in a float build.
Maybe @TerryE can answer this one?

**Comment by TerryE** [comment] 2017-05-12 19:04
The float version includes some "majic" in the `c_strtod()`, routine which is special to NOdeMCU builds.  If we change this then it might break other apps which assume this.  We are in the process of rebaselining NodeMCU on a Lua 5.3.4 baseline, but with 32 bit ints and floats (5.3.4 has separate number types for int and float.)   The main reason for this is speed: the ESP32 has H/W 32bit floating point, but 640bit is emulated in S/W.  We will introduce a userdata type for those that really want to have 64bit integer working.
