### ISSUE TITLE
System reboot cased by file.write()

### ISSUE THREAD

**Issue by guanglong108** [nodemcu/nodemcu-firmware#1204] opened 2016-03-30 02:47 UTC
Every time, when file size > 26857 Bytes and it opened by file.open(file_name,'a+'), then function file.write() and file.writeline() will lead to system reboot.

**Comment by jmattsson** [comment] 2016-03-30 04:18
Duplicate of #1149 ?

**Comment by marcelstoer** [comment] 2016-03-30 06:15
Oh, yes, good point.

**Closed by marcelstoer** 2016-03-30 06:15 UTC
