### ISSUE TITLE
Upgrade to SDK 1.4.0

### ISSUE THREAD

**Issue by eku** [nodemcu/nodemcu-firmware#677] opened 2015-10-04 14:11 UTC
Just to let you know that the toolchain has been updated to SDK 1.4.0 pfalcon/esp-open-sdk@2df0123
Please rebase nodeMCU on a newer SDK version.

**Comment by TerryE** [comment] 2015-10-14 08:07
Duplicate of #687 which is implementing this.

**Closed by TerryE** 2015-10-14 08:07 UTC

**Comment by eku** [comment] 2015-10-14 09:48
@TerryE an issue with a lower # cannot be a duplicate of a pull request with a higher #. Just my 2ct.

**Comment by TerryE** [comment] 2015-10-14 11:56
@eku, IMO when you start paying for the firmware or contributing to its development then you can validly make snide comments.  In the meantime some of us are putting a lot of effort into making this happen.  A thank-you would be more constructive.  This issue is still closed.
