### ISSUE TITLE
Can't build firmware image using the docker image(from official doc)

### ISSUE THREAD

**Issue by Dauren2495** [nodemcu/nodemcu-firmware#2804] opened 2019-06-21 09:42 UTC
Recently I pulled master branch of this repo and wanted to build firmware image using the [Docker Image](https://hub.docker.com/r/marcelstoer/nodemcu-build/) referenced in the official documentation, but I'm getting this error
``` bash
make -C app clean;
make[1]: Entering directory '/opt/nodemcu-firmware/app'
Makefile:23: *** missing separator.  Stop.
make[1]: Leaving directory '/opt/nodemcu-firmware/app'
Makefile:245: recipe for target 'clean' failed
make: *** [clean] Error 2
```
This Docker image used to work fine before I pulled latest version of the master branch

**Comment by marcelstoer** [comment] 2019-06-22 11:23
This is a support request for the Docker builder -> closing

That being said I just ran a build against the `master` branch as-is (i.e. no config changes) and couldn't reproduce this.

**Closed by marcelstoer** 2019-06-22 11:23 UTC
