### ISSUE TITLE
building esp32 fresh, make errors "ctype.h: No such file or directory"

### ISSUE THREAD

**Issue by danlu01** [nodemcu/nodemcu-firmware#2325] opened 2018-03-27 08:38 UTC
I'm trying the build nodemcu ESP32 on linux following this doc:
https://nodemcu.readthedocs.io/en/dev-esp32/en/build/

I installed Linux Mint 64bit in a Oracle VM.  Then ran:
git clone --branch dev-esp32 --recurse-submodules https://github.com/nodemcu/nodemcu-firmware.git nodemcu-firmware-esp32

When I try to run make, I got the following error:
daniel@daniel-VirtualBox ~/nodemcu-firmware-esp32 $ make
Setting IDF_PATH and re-invoking...
make[1]: Entering directory '/home/daniel/nodemcu-firmware-esp32'
make[2]: Entering directory '/home/daniel/nodemcu-firmware-esp32/sdk/esp32-esp-idf/tools/kconfig'
cc  -DCURSES_LOC="<curses.h>" -DLOCALE -MD   -c -o mconf.o mconf.c
mconf.c:11:19: fatal error: ctype.h: No such file or directory
compilation terminated.

What an I doing wrong?

**Comment by devsaurus** [comment] 2018-03-31 06:48
Can't reproduce this on `dev-esp32`.
I'll prepare an SDK update within the next days, maybe this has some positive side effects for your configuration.

**Comment by devsaurus** [comment] 2018-04-04 08:44
I've updated the SDK, but this error is most likely related to your build system.
Please double check that packages for glibc development are installed (e.g. `glibc-devel`).

**Comment by devsaurus** [comment] 2018-04-15 20:58
Closing, this is not a firmware issue.

**Closed by devsaurus** 2018-04-15 20:58 UTC
Labels: ESP32
