### ISSUE TITLE
打开配网功能编译失败smartconfig

### ISSUE THREAD

**Issue by 547176052** [nodemcu/nodemcu-firmware#3142] opened 2020-06-03 17:49 UTC
### Compile failed to open the distribution network function
```
xtensa-lx106-elf-gcc  -I ../../sdk-overrides/include -I /root/workspace/sdk/esp_iot_sdk_v3.0-e4434aa/include -D_C_TYPES_H_ -O2 -ffunction-sections -fno-jump-tables -fdata-sections -g -Wpointer-arith -Wundef -Werror -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals   -DMBEDTLS_USER_CONFIG_FILE=\"user_mbedtls.h\" -DLWIP_OPEN_SRC  -std=gnu11 -Wimplicit -I ../libc -I ../lua -I ../platform -I ../u8g2lib/u8g2/src/clib -I ../ucglib/ucg/src/clib -I ../ -I ../include   -o .output/eagle/debug/obj/wifi.o -c wifi.c
wifi.c:20:31: fatal error: smart/smartconfig.h: No such file or directory
 #include "smart/smartconfig.h"
                               ^
compilation terminated.
../../Makefile:422: recipe for target '.output/eagle/debug/obj/wifi.o' failed
make[2]: *** [.output/eagle/debug/obj/wifi.o] Error 1
make[2]: Leaving directory '/root/workspace/app/modules'
../Makefile:380: recipe for target '.subdirs' failed
make[1]: *** [.subdirs] Error 2
make[1]: Leaving directory '/root/workspace/app'
Makefile:380: recipe for target '.subdirs' failed
make: *** [.subdirs] Error 2
script returned exit code 2

```

**Comment by marcelstoer** [comment] 2020-06-03 20:09
Duplicate of #2928

**Closed by marcelstoer** 2020-06-03 20:09 UTC
